### PR TITLE
v2.0.0

### PR DESCRIPTION
**Pull request by whymarrh**
This PR represents the v2.0.0 release.

### CODE REVIEW

**Comment by Gudahtt** [comment]
FYI I had a bit more feedback on the TypeScript rules - might want to hold off on this release until those are updated

**Comment by whymarrh** [comment]
> FYI I had a bit more feedback on the TypeScript rules - might want to hold off on this release until those are updated

Where is this feedback?

**Comment by Gudahtt** [comment]
It's in a draft review - I'm not finished yet. The tl;dr is that a bunch of the typescript rules you added are deprecated.

**Comment by whymarrh** [comment]
See #27, I've updated the TS rules

**Pull request merged**
