### PR TITLE
jsdoc: remove deprecated rule jsdoc/newline-after-description

### PR DESCRIPTION
**Pull request by legobeat**
Will be causing error starting with eslint-plugin-jsdoc@43

https://github.com/gajus/eslint-plugin-jsdoc/issues/1031

### CODE REVIEW

**Comment by Mrtenz** [comment]
From the [plugin release](https://github.com/gajus/eslint-plugin-jsdoc/releases/tag/v42.0.0):

> 1. Removes `jsdoc/newline-after-description` rule in favor of `jsdoc/tag-lines` with option `startLines: 0` for "never" and `startLines: 1` for "always". Defaults now to `startLines: 0`

Should we add `jsdoc/tag-lines`?

**Comment by Mrtenz** [comment]
> > From the [plugin release](https://github.com/gajus/eslint-plugin-jsdoc/releases/tag/v42.0.0):
> > > 1. Removes `jsdoc/newline-after-description` rule in favor of `jsdoc/tag-lines` with option `startLines: 0` for "never" and `startLines: 1` for "always". Defaults now to `startLines: 0`
> > 
> > 
> > Should we add `jsdoc/tag-lines`?
> 
> Doing so would mean this rule would not be usable in Node.js 14. I don't see the rush.

Well, I don't think we want JSDoc comments without a line between the description and params.

And since Node.js 14 is EOL, I don't see why we couldn't update this rule?

**Comment by Gudahtt** [comment]
I don't think we need to worry about compatibility with packages that violate the `peerDependency` requirements, which are currently:

>"eslint-plugin-jsdoc": "^39.6.2",

Agreed with @Mrtenz that it seems better to keep this rule until we can replace it. Unless we decide we don't want it anymore at least. I don't really see the case for dropping this rule so early that we can't yet use its replacement.

**Comment by Gudahtt** [comment]
>Doing so would mean this rule would not be usable in Node.js 14

This rule appears to be present in 43.0.7 :thinking:  https://github.com/gajus/eslint-plugin-jsdoc/blob/v43.0.7/src/rules/tagLines.js

**Comment by mcmire** [comment]
Do we still want to do this now that https://github.com/MetaMask/eslint-config/pull/288 has been merged?

**Comment by Gudahtt** [comment]
Makes sense. As long as we replace it soon, I'm OK with removing it.

Migrating between these rules in lockstep would force us into a very narrow range for that peer dependency, which would be a bit awkward to deal with.

**Review by Gudahtt — APPROVED** [review]
LGTM!

**Pull request merged**
