### PR TITLE
add prettierrc.yml

### PR DESCRIPTION
**Pull request by brad-decker**
### preface
I have prettier for vscode installed with the option set to not format if a configuration file cannot be found.

I noticed, however, that on save it was turning single quote strings to double quote, which then showed as an error due to our eslint config.

Because this repo has an `.editorconfig` file, the prettier vscode plugin says "oh okay you really want me to format your files" and it follows the specs of that file. So I added the `.prettierrc.yml` file to prevent this behavior for anyone who might have my same experience.

### CODE REVIEW

**Review by Gudahtt — APPROVED** [review]
Sure, this seems harmless.

Related question: why is `prettier` not in the `devDependencies`? :thinking: Seems like an oversight.

**Review by ryanml — APPROVED** [review]
lgtm!

**Review by rekmarks — CHANGES_REQUESTED** [review]
Huh, that makes sense. `quoteProps` should be set to `consistent`, however: https://github.com/MetaMask/eslint-config/blob/9a19af4/packages/base/src/index.js#L23

**Comment by rekmarks** [comment]
@Gudahtt you mean in the root manifest? We can definitely add that if not. It's in the `base` manifest.

**Comment by Gudahtt** [comment]
Exactly, in the root manifest. We use ESLint in the root (the `lint` script), but it's not listed as a dependency.

**Comment by brad-decker** [comment]
added quoteProps consistent!

**Review by rekmarks — APPROVED** [review]
LGTM!

**Pull request merged**
