### PR TITLE
Add JSDoc ESLint rules

### PR DESCRIPTION
**Pull request by Gudahtt**
ESLint rules for JSDoc have been added to the base package and to the TypeScript package, using the `eslint-plugin-jsdoc` plugin. These rules should help improve the quality of our inline documentation.

This was done primarily to prepare for the generation of HTML documentation using TypeDoc. Our inline documentation needs to be of a higher quality than it is now for that to work out well.

These rules have been tested with [`metamask-extension`](https://github.com/MetaMask/metamask-extension/pull/12112),
[`@metamask/controllers`](https://github.com/MetaMask/controllers/pull/591), and [`@metamask/eth-sig-util`](https://github.com/MetaMask/eth-sig-util/pull/206). See those PRs to get an idea of what these rules look like in practice.

### CODE REVIEW

**Review by darkwing — APPROVED** [review]

**Review by rekmarks — COMMENTED** [review]
This LGTM, but we don't we just extend the recommended rule set and then specify the rules we care abouit?

```
{
  "extends": ["plugin:jsdoc/recommended"]
}
```

**Comment by Gudahtt** [comment]
I would except that the recommended ruleset has each one set to "warning". I figured we wanted them to error instead, so that CI can tell is when they're violated.

**Review by rekmarks — APPROVED** [review]
LGTM!

**Comment by rekmarks** [comment]
> I would except that the recommended ruleset has each one set to "warning". I figured we wanted them to error instead, so that CI can tell is when they're violated.

Also they use numbers in their docs (and possibly also config) which sucks and is why I didn't realize this!

**Pull request merged**
