### PR TITLE
Disable more undesired syntax

### PR DESCRIPTION
**Pull request by rekmarks**
This PR expands the kinds of JavaScript syntax we forbid using the [`no-restricted-syntax`](https://eslint.org/docs/rules/no-restricted-syntax) rule to include:
- `with` statements
  - Because `with` is very strange and we don't have a use case for it!
- Function expressions
  - Because they're useless and weird! Just use arrow functions.
  - Note that a _function expression_ is of the form `const foo = function () { /* do something */ };`, and is not to be confused with _function declarations_, e.g. `function bar () { /* do something */ };`
- The `in` operator
  - Because the property lookup walks the prototype chain, wherefore e.g. `'toString' in {}` evaluates to `true`. We should practically always use `Reflect.hasOwnProperty` instead.

### CODE REVIEW

**Comment by Gudahtt** [comment]
>The instanceof operator, except if the right-hand operand is Error

I just thought of another use case for `instanceof`: custom error classes. e.g. https://github.com/MetaMask/auto-changelog/blob/94354653254e6c616efc9135c600c09961335740/src/cli.ts#L132

**Comment by mcmire** [comment]
I think if we removed the `instanceof` rule for now then I would be good with this!

**Comment by Gudahtt** [comment]
Agreed. Especially with TypeScript v4.4, I expect that `instanceof` with custom error classes will be a fairly common occurrence.

**Comment by rekmarks** [comment]
@Gudahtt @mcmire I removed this:

> - The `instanceof` operator, _except_ if the right-hand operand is `Error`
>   - `instanceof` checks if the prototype of the two operands are the same. We can almost never be assured of this, except for globals like `Error`. We should just make explicit exceptions for this operator for those rare exceptions.

**Review by mcmire — APPROVED** [review]
Sweet, looks good!

**Comment by Gudahtt** [comment]
I am in favour of this as well. I can approve after the conflicts are resolved, and once v10 has been published. Better to keep this for the v11 release to avoid making the v10 update too challenging.

**Review by Gudahtt — APPROVED** [review]

**Pull request merged**
