### PR TITLE
Remove `@typescript-config/consistent-type-definition` rule

### PR DESCRIPTION
**Pull request by Gudahtt**
The `@typescript-config/consistent-type-definition` rule has been removed because it tries to force the use of interfaces over types in scenarios where interfaces don't work due to [incompatibilities with `Record<string, unknown>`](https://github.com/Microsoft/TypeScript/issues/15300#issuecomment-702872440).

We could consider forcing the use of types over interfaces instead, but I prefer using interfaces in some situations. They seem simpler to write and understand sometimes. So for now it seems best to just remove the rule.

This rule has [already been disabled in the `@metamask/controllers` repository](https://github.com/MetaMask/controllers/blob/8134da08a03fb63b146f8a3cffcb5e78fb70d58b/.eslintrc.js#L36).

### CODE REVIEW

**Review by mcmire — APPROVED** [review]
Makes sense to me.

**Comment by rekmarks** [comment]
While I agree that interfaces are nicer to write, I think the cons of mixing types and interfaces are outweighed by the benefits of sticking to just one or the other.

Because interfaces are incompatible with the `BaseControllerV2` state type, the thing we have to stick to must be types. In addition, interfaces have weird edge cases and don't play as nicely with modern TypeScript features as types do.

Meanwhile, classes can still `extend` types, and that’s the only thing interfaces are good for that I can’t do without.

**Comment by Gudahtt** [comment]
One advantage to interfaces is declaration merging, i.e. you can declare the same name multiple times and the definitions are merged together. This is convenient for typing global APIs like `window` and `document`, because you can build out a definition just for the parts you use without conflicting with other interface declarations for the same API that reference different properties.

Aside from that one exception, I guess we could enforce the use of types :thinking:.

**Comment by Gudahtt** [comment]
We decided to go with #216 instead

**Pull request closed without merging**
