### PR TITLE
update jest/lowercase-name -> jest/prefer-lowercase-title

### PR DESCRIPTION
**Pull request by adonesky1**
The jest eslint rule `jest/lowercase-name` has been updated to `jest/prefer-lowercase-title`: https://github.com/jest-community/eslint-plugin-jest/blob/main/docs/rules/prefer-lowercase-title.md

### CODE REVIEW

**Review by mcmire — DISMISSED** [review]
According to [this commit](https://github.com/jest-community/eslint-plugin-jest/commit/b8600841e371d5d9f36be4e50e53252fd8f62734), this seems to have been changed in `eslint-plugin-jest` 25.0.0. Thanks for fixing this!

**Review by Gudahtt — CHANGES_REQUESTED** [review]
This package still uses v24 of the Jest plugin: https://github.com/MetaMask/eslint-config/blob/main/packages/jest/package.json#L37

So this change hasn't been made yet in our version. We would need to update that first.

**Comment by mcmire** [comment]
@Gudahtt Hmm. If a package upgrades `@metamask/eslint-config-jest`, and you run Yarn, will Yarn automatically upgrade `eslint-config-jest` too?

**Comment by Gudahtt** [comment]
Nope. With Yarn, peer dependencies would need to be manually updated, so effectively they'd require a major version update for this config, where the need to update the Jest plugin was listed as a breaking change.

**Comment by mcmire** [comment]
Slightly off topic, but now I have another question. Why did we choose to add `eslint-plugin-jest` as a peer dependency? If we change our shared config so that the consumer needs another version of Jest to use the config -- i.e., the lint step won't pass unless it has this new version -- then why not make Jest a dev dependency?

**Comment by Gudahtt** [comment]
@mcmire I'm not sure what you mean. Making `eslint-plugin-jest` a peer dependency instructs projects using this lint config about which plugin version these rules require. If we made it a dev dependency, they'd have no idea why it failed when the version didn't match. This way, they see a clear warning upon install when the version used is not compatible.

**Comment by Gudahtt** [comment]
>Is there any reason this update couldn't happen in this PR?

Sure, you could do that. But typically when we update one of these ESLint plugin dependencies, we'll review the changes to make sure our config remains compatible, and to ensure we're taking advantage of any new rules or changes that seem beneficial. So the PR would no longer be just about this one rule if you did that.

It looks like you've increased the plugin version by _two_ major versions in this PR. The latest version states that it is incompatible with the typescript ESLint plugin that we use, so that seems like a non-starter already.

**Comment by Gudahtt** [comment]
Superceded by #228

**Pull request closed without merging**
