### PR TITLE
chore(devdeps): @lavamoat/allow-scripts@^2.3.1->^3.0.4

### PR DESCRIPTION
**Pull request by legobeat**
Security-related maintenance upgrade of `@lavamoat/allow-scripts`.

### CODE REVIEW

**Comment by mcmire** [comment]
Makes sense! Just needs to resolve conflicts.

**Comment by legobeat** [comment]
> Makes sense! Just needs to resolve conflicts.

Turns out this was already applied as part of #356 but then not reverted in #357.

@Mrtenz Intentional?

**Comment by Mrtenz** [comment]
@legobeat This was applied in #351, which wasn't reverted. 😅

**Comment by legobeat** [comment]
@Mrtenz My bad, thanks for clarifying!

**Pull request closed without merging**
